### PR TITLE
fix: postgres durable state schemaName change leads to write errors (#275)

### LINKED ISSUE #275: jdbc-durable-state-store for postgres schemaName is ignored / leads to errors
Given:

- Pekko Persistence schema is created in postgres with schema changed (f.e. pekko)
- Application is configured for durable state actors

When:

Changing schemaName in .conf file for jdbc-durable-state-store to f.e. "pekko" leads to error:

```
org.apache.pekko.persistence.typed.state.internal.DurableStateStoreException: Failed to persist state with sequence number [1] for persistenceId [X]
...
Caused by: org.postgresql.util.PSQLException: ERROR: relation "durable_state" does not exist
```

### PR DESCRIPTION
**Pull request by patsta32**
closes #275

### CODE REVIEW

File: core/src/main/scala/org/apache/pekko/persistence/jdbc/config/PekkoPersistenceConfig.scala [hunk 1]
```diff
@@ -223,6 +223,7 @@ class DurableStateTableConfiguration(config: Config) {
   val columnNames: DurableStateTableColumnNames = new DurableStateTableColumnNames(config)
   val stateSequenceConfig = DurableStateSequenceRetrievalConfig(config)
   override def toString: String = s"DurableStateTableConfiguration($tableName,$schemaName,$columnNames)"
+  def schemaAndTableName: String = schemaName.map(_ + ".").getOrElse("") + tableName
```
[the remark this answers is not in the document]
Comment (pjfanning) [reply core/src/main/scala/org/apache/pekko/persistence/jdbc/config/PekkoPersistenceConfig.scala:226]: please don't `+` strings - use String interpolation or something like that

File: core/src/main/scala/org/apache/pekko/persistence/jdbc/testkit/internal/SchemaType.scala [hunk 2]
```diff
@@ -26,6 +26,11 @@ import org.apache.pekko.annotation.InternalApi
  */
 @InternalApi private[jdbc] case object Postgres extends SchemaType
 
+/**
+ * INTERNAL API
+ */
+@InternalApi private[jdbc] case object PostgresPekkoSchema extends SchemaType
```
Comment (pjfanning) [inline core/src/main/scala/org/apache/pekko/persistence/jdbc/testkit/internal/SchemaType.scala:32]: Again, I don't know why we need a new schema type, I would prefer to fix the existing Postgres one.

File: core/src/main/resources/schema/postgres/postgres-create-schema-pekko.sql [hunk 3]
```diff
@@ -0,0 +1,64 @@
+CREATE SCHEMA IF NOT EXISTS pekko;
```
[the remark this answers is not in the document]
Comment (pjfanning) [reply core/src/main/resources/schema/postgres/postgres-create-schema-pekko.sql:1]: if we can't change the existing postgres sql files - could we just produce a diff sql that can be run like this?
* run existing postgres script
* optionally run an additional script to get the change in behaviour that you want

**Review by pjfanning — CHANGES_REQUESTED** [review]

File: core/src/main/resources/schema/postgres/postgres-create-schema-pekko.sql (hunk 3 above)
[the remark this answers is not in the document]
Comment (patsta32) [reply core/src/main/resources/schema/postgres/postgres-create-schema-pekko.sql:1]: I created a move-schema.sql to avoid editing the default postgres-create-schema.sql, because it is used as a default reference in [Pekko-JDBC Database Schema Docs](https://pekko.apache.org/docs/pekko-persistence-jdbc/current/configuration.html#database-schema)

File: core/src/main/scala/org/apache/pekko/persistence/jdbc/config/PekkoPersistenceConfig.scala [hunk 4]
```diff
@@ -221,7 +221,10 @@ class DurableStateTableConfiguration(config: Config) {
   val batchSize: Int = config.getInt("batchSize")
   val schemaName: Option[String] = cfg.asStringOption("schemaName")
   val columnNames: DurableStateTableColumnNames = new DurableStateTableColumnNames(config)
-  val stateSequenceConfig = DurableStateSequenceRetrievalConfig(config)
+  val stateSequenceConfig: DurableStateSequenceRetrievalConfig = DurableStateSequenceRetrievalConfig(config)
+  private val schemaPrefix: String = schemaName.fold("")(schema => s"$schema.")
+  // @since "1.1.1"
```
Comment (pjfanning) [inline core/src/main/scala/org/apache/pekko/persistence/jdbc/config/PekkoPersistenceConfig.scala:226]:
```
/**
 * @since 1.1.1
 */
```

Comment (pjfanning) [reply core/src/main/scala/org/apache/pekko/persistence/jdbc/config/PekkoPersistenceConfig.scala:226]: this scaladoc since tag is supported by IDEs and appears in the genearted scaladocs

File: integration-test/src/test/scala/org/apache/pekko/persistence/jdbc/integration/AllPersistenceIdsTest.scala [hunk 5]
```diff
@@ -9,13 +9,7 @@
...
 package org.apache.pekko.persistence.jdbc.integration
 
-import org.apache.pekko.persistence.jdbc.query.{
-  AllPersistenceIdsTest,
-  MysqlCleaner,
-  OracleCleaner,
-  PostgresCleaner,
-  SqlServerCleaner
-}
+import org.apache.pekko.persistence.jdbc.query.{AllPersistenceIdsTest, MysqlCleaner, OracleCleaner, PostgresCleaner, SqlServerCleaner}
```
Comment (pjfanning) [inline integration-test/src/test/scala/org/apache/pekko/persistence/jdbc/integration/AllPersistenceIdsTest.scala:12]: please use `sbt scalafmtAll` yo properly format the code

**Comment by patsta32** [comment]
@pjfanning Sorry for the previous push. I reworked the whole PR, now the state is reviewable. 
I hope this meets the expectation set in #275 comments. Thank you for your patience!

File: core/src/test/scala/org/apache/pekko/persistence/jdbc/state/scaladsl/DurableStateStorePluginSpec.scala [hunk 6]
```diff
@@ -11,14 +11,23 @@ package org.apache.pekko.persistence.jdbc.state.scaladsl
 
 import com.typesafe.config.{ Config, ConfigFactory }
 import org.apache.pekko
+import org.apache.pekko.persistence.jdbc.config.SlickConfiguration
```
Comment (pjfanning) [inline core/src/test/scala/org/apache/pekko/persistence/jdbc/state/scaladsl/DurableStateStorePluginSpec.scala:14]: * with these imports, remove the org.apache bit
* we have already have `import org.apache.pekko`
* please order them below the `import pekko.actor._`

File: core/src/test/scala/org/apache/pekko/persistence/jdbc/state/scaladsl/DurableStateStorePluginSpec.scala [hunk 7]
```diff
@@ -45,5 +54,90 @@ abstract class DurableStateStorePluginSpec(config: Config, profile: JdbcProfile)
...
+  lazy val db = SlickDatabase.database(
+    config,
+    new SlickConfiguration(config.getConfig("slick")), "slick.db"
+  )
+
+  private val createSchema = s"CREATE SCHEMA IF NOT EXISTS $schemaName;"
+  private val moveDurableStateTableToSchema = s"alter table public.durable_state set schema $schemaName;"
+  private val moveDurableStateTableToPublic = s"alter table $schemaName.durable_state set schema public;"
+  private val createSchemaAndMoveTable = s"${createSchema}${moveDurableStateTableToSchema}"
+  private val removeTableFromSchema = s"${moveDurableStateTableToPublic}"
```
Comment (pjfanning) [inline core/src/test/scala/org/apache/pekko/persistence/jdbc/state/scaladsl/DurableStateStorePluginSpec.scala:96]: no need for string interpolation on this line

File: core/src/test/scala/org/apache/pekko/persistence/jdbc/state/scaladsl/DurableStateStorePluginSpec.scala [hunk 8]
```diff
@@ -11,14 +11,23 @@ package org.apache.pekko.persistence.jdbc.state.scaladsl
...
+import org.apache.pekko.util.Timeout
 import pekko.actor._
 import org.scalatest.matchers.should.Matchers
 import org.scalatest.wordspec.AnyWordSpecLike
-import org.scalatest.BeforeAndAfterAll
+import org.scalatest.{ BeforeAndAfterAll, BeforeAndAfterEach }
+import org.scalatest.concurrent.Eventually.eventually
 import org.scalatest.concurrent.ScalaFutures
+import org.scalatest.time.{ Millis, Seconds, Span }
 import pekko.persistence.state.DurableStateStoreRegistry
```
Comment (pjfanning) [inline core/src/test/scala/org/apache/pekko/persistence/jdbc/state/scaladsl/DurableStateStorePluginSpec.scala:26]: this pekko import should be with the other pekko imports

**Comment by patsta32** [comment]
@pjfanning sure, already pushed the requested change!

**Comment by pjfanning** [comment]
The Postgres integration tests are failing. A seemingly unrelated test. I'm not sure if it the same test that is part of what is blocking my PR.

**Review by pjfanning — APPROVED** [review]
lgtm
